platform :ios, '11.0'
use_frameworks!

target 'ViteBusiness_Example' do
  pod 'ViteBusiness', :path => '../'

  pod 'ViteWallet', :path => '../../vite-wallet-ios/'
#  pod 'ViteWallet', :git => 'https://github.com/vitelabs/vite-swift-kit.git', :commit => 'faf08c7463ed670c2f70ad9de6658770305053c1'

#  pod 'Vite_GrinWallet', :path => '../../Vite_GrinWallet/'
  pod 'Vite_GrinWallet', :git => 'https://github.com/vitelabs/vite-grin-wallet-ios.git', :commit => '4f1141a131e223a5a41686d2e9efa636e3f1ee24'
  pod 'Vite_HDWalletKit', :git => 'https://github.com/vitelabs/vite-hd-wallet-kit-ios.git', :commit => 'afffc6fb34690e49ae94f2fd796032e08f487c53'
  pod 'BinanceChain', :git => 'https://github.com/vitelabs/SwiftBinanceChain.git'

  pod 'SnapKit', '~> 4.0.0'
  pod 'BigInt', '~> 4.0'
  pod 'R.swift', '5.0.0.alpha.3'
  pod 'JSONRPCKit', '~> 3.0.0'
  pod 'PromiseKit', '~> 6.8.4'
  pod 'APIKit'
  pod 'ObjectMapper'
  pod 'MBProgressHUD'
  pod 'KeychainSwift', '13.0.0'
  pod 'Moya'
  pod 'MJRefresh', '3.1.15.7'
  pod 'KMNavigationBarTransition'
  pod 'XCGLogger', '~> 7.0'
  pod 'pop', '~> 1.0'
  pod 'DACircularProgress', '2.3.1'
  pod 'Kingfisher', '~> 4.0'
  pod 'NYXImagesKit', '2.3'

#  pod 'Charts', :git => 'https://github.com/danielgindi/Charts.git', :tag => 'v3.4.0'
  pod 'Charts', '3.5.0'


  #request
  pod 'SwiftyJSON'

  #statistics
  pod 'BaiduMobStat'

  #UI Control
  pod 'ActionSheetPicker-3.0'
  pod 'MBProgressHUD'
  pod 'Toast-Swift', '~> 4.0.1'
  pod 'RazzleDazzle'
  pod 'CHIPageControl'

  #table static form
  pod 'Eureka', '~> 5.3.0'

  #RX
  pod 'RxSwift', '~> 4.0'
  pod 'RxCocoa'
  pod 'RxDataSources', '~> 3.0'
  pod 'NSObject+Rx'
  pod 'RxOptional'
  pod 'RxGesture'
  pod 'Then'
  pod 'Action'
  pod 'ReusableKit', '~> 2.1.0'
  pod 'ReactorKit'

  #code review
  pod 'SwiftLint', '0.31.0'

  #crash
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'Firebase/Core'
  pod 'Firebase/Analytics'
  pod 'Firebase/Performance'
  pod 'Firebase/RemoteConfig'

  pod 'Bagel', '~>  1.3.2'

  pod 'FSPagerView'

  target 'ViteBusiness_Tests' do
    inherit! :search_paths
    pod 'R.swift', '5.0.0.alpha.3'

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end

target 'UpdateRswift' do
  pod 'R.swift', '5.0.0.alpha.3'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        if ['RazzleDazzle', 'JSONRPCKit', 'APIKit'].include? target.name
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '4.0'
            end
        end
    end
end
