
// Objective-C API for talking to the following Go packages
//
//	github.com/vitelabs/go-vite/mobile/crypto
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Crypto_FRAMEWORK_H__
#define __Crypto_FRAMEWORK_H__

#include "Crypto.objc.h"
#include "universe.objc.h"

#endif
