// Objective-C API for talking to github.com/vitelabs/go-vite/mobile/crypto Go package.
//   gobind -lang=objc github.com/vitelabs/go-vite/mobile/crypto
//
// File is generated by gobind. Do not edit.

#ifndef __Crypto_H__
#define __Crypto_H__

@import Foundation;
#include "Universe.objc.h"


@class CryptoEd25519KeyPair;
@class CryptoSignDataResult;

@interface CryptoEd25519KeyPair : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
- (NSData*)publicKey;
- (void)setPublicKey:(NSData*)v;
- (NSData*)privateKey;
- (void)setPrivateKey:(NSData*)v;
@end

@interface CryptoSignDataResult : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
- (NSData*)publicKey;
- (void)setPublicKey:(NSData*)v;
- (NSData*)message;
- (void)setMessage:(NSData*)v;
- (NSData*)signature;
- (void)setSignature:(NSData*)v;
@end

FOUNDATION_EXPORT NSData* CryptoAesCTRXOR(NSData* key, NSData* inText, NSData* iv, NSError** error);

FOUNDATION_EXPORT NSData* CryptoComputeSecret(NSData* private, NSData* peersPublic, NSError** error);

FOUNDATION_EXPORT NSData* CryptoEd25519PrivToCurve25519(NSData* ed25519Priv);

FOUNDATION_EXPORT NSData* CryptoEd25519PubToCurve25519(NSData* ed25519Pub);

FOUNDATION_EXPORT CryptoEd25519KeyPair* CryptoGenerateEd25519KeyPair(NSData* seed, NSError** error);

FOUNDATION_EXPORT NSData* CryptoHash(long size, NSData* data);

FOUNDATION_EXPORT NSData* CryptoHash256(NSData* data);

FOUNDATION_EXPORT CryptoSignDataResult* CryptoSignData(NSData* priv, NSData* message);

FOUNDATION_EXPORT BOOL CryptoVerifySignature(NSData* pub, NSData* message, NSData* signData, BOOL* ret0_, NSError** error);

#endif
