
// Objective-C API for talking to the following Go packages
//
//	github.com/vitelabs/go-vite/mobile/ioscrypto
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Ioscrypto_FRAMEWORK_H__
#define __Ioscrypto_FRAMEWORK_H__

#include "Ioscrypto.objc.h"
#include "universe.objc.h"

#endif
